trigger:
  branches:
    include:
      - master
      - dev

pool:
  vmImage: 'ubuntu-latest'
  
variables: 
- group: Build-Variable-Group
- name: MAVEN_CACHE_FOLDER
  value: $(Pipeline.Workspace)/.m2/repository
- name: MAVEN_OPTS
  value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

stages:
- stage: BuildStage
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
      - task: CacheBeta@0
        displayName: Cache Maven local repo
        inputs:
          key: $(Build.SourcesDirectory)/pom.xml
          path: $(MAVEN_CACHE_FOLDER)
    
      - task: DownloadSecureFile@1
        name: settings
        displayName: Download secure file
        inputs:
          secureFile: 'settings.xml'

      - task: Maven@3
        displayName: Maven Build
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean package -DskipTests -s $(settings.secureFilePath)'
          mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

- stage: DevelopmentStage
  displayName: Deploy to Development Environment
  dependsOn: BuildStage
  jobs:
    - job: DevDeploy
      displayName: Deploy To Dev Environment
      steps:
        - task: CacheBeta@0
          displayName: Cache Maven local repo
          inputs:
            key: $(Build.SourcesDirectory)/pom.xml
            path: $(MAVEN_CACHE_FOLDER)
            
        - task: DownloadSecureFile@1
          name: settings
          displayName: Download Settings File
          inputs:
            secureFile: 'settings.xml'

        - task: Maven@3
          inputs:
           mavenPomFile: 'pom.xml'
           goals: 'deploy $(MAVEN_OPTS)  -DmuleDeploy -Dserver=$(server) -Denvironment=$(environment) -Dworker=$(worker) -DworkerType=$(workerType) -Dapp.runtime=$(app.runtime) -Dapp.name=$(app.name) -Dproject.name=$(project.name) -Dproject.version=$(project.version) -Dmule.env=$(mule.env) -Dmule.key=$(mule.key) -DattachMuleSources -DskipMunitTests -s $(settings.secureFilePath)'
           mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
           publishJUnitResults: false
           javaHomeOption: 'JDKVersion'
           jdkVersionOption: '1.8'
           jdkArchitectureOption: 'x64'
           mavenVersionOption: 'Default'
           mavenAuthenticateFeed: false